### ISSUE TITLE
aresponses does not work with aiohttp v3.8.1

### ISSUE THREAD

**Issue by robertBrnnn** [aresponses/aresponses#74]
After upgrading from aiohttp v3.7.4.post0 to version 3.8.1, my aresponses test cases fail with the below: 
```
Traceback (most recent call last):
  File "../lib/python3.6/site-packages/aiohttp/web_protocol.py", line 602, in finish_response
    prepare_meth = resp.prepare
AttributeError: 'NoneType' object has no attribute 'prepare'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../lib/python3.6/site-packages/aiohttp/web_protocol.py", line 514, in start
    resp, reset = await task
  File "../lib/python3.6/site-packages/aiohttp/web_protocol.py", line 460, in _handle_request
    reset = await self.finish_response(request, resp, start_time)
  File "../lib/python3.6/site-packages/aiohttp/web_protocol.py", line 605, in finish_response
    raise RuntimeError("Missing return " "statement on request handler")
RuntimeError: Missing return statement on request handler
```

If I downgrade to 3.7.4.post0 I don't experience this issue.

**Comment by Olegt0rr** [comment]
The same issue

**Comment by brycedrennan** [comment]
If someone can provide an example I can look into this. I don't doubt something isn't working but the test suite is passing for me on 3.8.1

**Comment by brycedrennan** [comment]
Seems like this is likely related to python 3.6.  I've now [added thorough testing of all supported versions of python and aiohttp](https://github.com/aresponses/aresponses/pull/77). 

So I'm going to close this for now but can re-open if we learn more.
